// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require, exports) {
    return {
      get: function(url, success, fail) {
        var req;
        req = new XMLHttpRequest;
        req.open("GET", url);
        req.send();
        return req.onload = function() {
          var data;
          if (req.status === 200) {
            data = JSON.parse(req.responseText);
            if (success != null) {
              return success(data);
            }
          } else {
            return fail(req === (fail != null));
          }
        };
      },
      post: function(url, data, success, fail) {
        var req;
        req = new XMLHttpRequest;
        req.open("POST", url);
        req.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
        req.send(JSON.stringify(data));
        return req.onload = function(res) {
          if (req.status === 200) {
            data = JSON.parse(req.responseText);
            if (success != null) {
              return success(data);
            }
          } else {
            return fail(req === (fail != null));
          }
        };
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=ajax.map
*/
