// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  var success, warn, _ref;
  _ref = require("./notify"), success = _ref.success, warn = _ref.warn;
  exports.search = function(key, call) {
    return $.post("/search", {
      key: key
    }, call);
  };
  exports.fetch = function(data, call) {
    var item;
    item = {
      id: data.id
    };
    return $.post("/fetch", item, call);
  };
  exports.auth = function(password) {
    return $.post("/auth", {
      password: password
    }, function(result) {
      if (result.auth) {
        return success("Logined", "password saved");
      } else {
        return warn("Failed to login", "please login later");
      }
    });
  };
  return exports;
});
