// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  var config, error, info, password, popup, search, success, warn, _ref;
  _ref = require("./notify"), success = _ref.success, warn = _ref.warn, info = _ref.info, error = _ref.error;
  popup = require("./popup");
  config = require("./config");
  search = require("./search");
  exports.auth = function(password) {
    return $.post("/auth", {
      password: password
    }, function(result) {
      if (result.auth) {
        success("Logined", "password saved");
        popup.hide();
        return $("#login").slideUp();
      } else {
        return warn("Failed to login", "please login later");
      }
    });
  };
  password = (localStorage.getItem("password")) || "";
  if (password.length > config.min_password) {
    exports.auth(password);
  }
  exports.fetch = function(data, call) {
    data.password = password;
    return $.post("/fetch", data, call);
  };
  exports.update = function(data, call) {
    var _ref1, _ref2;
    data.password = password;
    if (!(((_ref1 = data.title) != null ? _ref1.length : void 0) > config.min_title)) {
      return error("No Title", "Can't post without title");
    } else if (!(((_ref2 = data.content) != null ? _ref2.length : void 0) > config.min_content)) {
      return error("Bad article", "too few words here");
    } else {
      return $.post("/update", data, function(result) {
        if (result.auth) {
          search.update();
          return success("Updated", "blog is ok");
        } else {
          return error("Failed", "failed to update");
        }
      });
    }
  };
  exports.get_index = function(call) {
    return $.getJSON("/get_index", function(json) {
      return call(json);
    });
  };
  exports.remove = function(data, call) {
    data.password = password;
    return $.post("/remove", data, function(result) {
      if (result.auth) {
        search.update();
        success("Got response", "Should be fine");
        return call();
      } else {
        return error("Failed", "need to login");
      }
    });
  };
  return exports;
});
