// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  exports.config = {
    warning_timeOut: 1000,
    error_timeOut: 1000,
    success_timeOut: 1000,
    info_timeOut: 1000,
    fadeIn_duration: 300,
    fadeOut_duration: 200,
    min_title: 2,
    min_content: 2,
    min_password: 4
  };
  return exports.config;
});
