// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  var popup;
  popup = $("#popup").hide();
  $("body").keydown(function(e) {
    log(e.keyCode);
    switch (e.keyCode) {
      case 27:
        return popup.fadeOut();
    }
  });
  require("./search");
  return exports;
});
