// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  var config;
  config = require("./config");
  exports.success = function(title, message) {
    toastr.timeOut = config.success_timeOut;
    return toastr.error(title, message);
  };
  exports.warn = function(title, message) {
    toastr.timeOut = config.warning_timeOut;
    return toastr.warning(title, message);
  };
  exports.info = function(title, message) {
    toastr.timeOut = config.info_timeOut;
    return toastr.info(title, message);
  };
  exports.error = function(title, message) {
    toastr.timeOut = config.error_timeOut;
    return toastr.error(title, message);
  };
  return exports;
});
