// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  exports.success = function(title, message) {
    toastr.timeOut = 2000;
    return toastr.error(title, message);
  };
  exports.warn = function(title, message) {
    toastr.timeOut = 3000;
    return toastr.warning(title, message);
  };
  exports.info = function(title, message) {
    toastr.timeOut = 3000;
    return toastr.warn(title, message);
  };
  exports.error = function(title, message) {
    toastr.timeOut = 5000;
    return toastr.warn(title, message);
  };
  return exports;
});
