// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  var ajax, article, auth, editor, login, paper, popup;
  exports.elem = popup = $("#popup");
  paper = $("#paper");
  login = $("#login");
  ajax = require("./ajax");
  login.click(function() {
    return exports.auth();
  });
  article = function(data) {
    return $(lilyturf.dom(function() {
      return this.div({
        "class": "article"
      }, this.div({
        "class": "title"
      }, this.text(data.title)), this.div({
        "class": "time"
      }, this.text(data.time)), this.div({
        "class": "content"
      }, this.text(data.content)));
    }));
  };
  auth = function() {
    var elem;
    elem = lilyturf.dom(function() {
      return this.input({
        "class": "password"
      });
    });
    $(elem).keydown(function(e) {
      var password, _ref;
      if ((_ref = e.keyCode) === 13 || _ref === 32) {
        password = $(elem).val();
        ajax.auth(password);
        return localStorage.setItem("password", password);
      }
    });
    return $(lilyturf.dom(function() {
      return this.div({
        "class": "auth"
      }, elem);
    }));
  };
  editor = function(data) {
    return $(lilyturf.dom(function() {
      return this.div({
        "class": "editor"
      }, this.input({
        "class": "title"
      }), this.textarea({
        "class": "content"
      }), this.button({
        "class": "save"
      }, this.text("save")));
    }));
  };
  exports.article = function(data) {
    popup.fadeIn();
    return ajax.fetch(data, function(item) {
      data.content = item.content;
      data.time = item.time;
      return paper.empty().append(article(data));
    });
  };
  exports.auth = function() {
    popup.fadeIn();
    return paper.empty().append(auth());
  };
  exports.editor = function(data) {
    popup.fadeIn();
    return ajax.fetch(data, function(item) {
      data.content = item.content;
      return paper.empty().append(editor(data));
    });
  };
  return exports;
});
